// Code generated by "enumer -type=Keyword"; DO NOT EDIT.

package parse

import (
	"fmt"
	"strings"
)

const _KeywordName = "KeywordUnspecifiedKeywordAllKeywordAndKeywordAnyKeywordArrayKeywordAsKeywordAscKeywordAssertRowsModifiedKeywordAtKeywordBetweenKeywordByKeywordCaseKeywordCastKeywordCollateKeywordContainsKeywordCreateKeywordCrossKeywordCubeKeywordCurrentKeywordDefaultKeywordDefineKeywordDescKeywordDistinctKeywordElseKeywordEndKeywordEnumKeywordEscapeKeywordExceptKeywordExcludeKeywordExistsKeywordExtractKeywordFalseKeywordFetchKeywordFollowingKeywordForKeywordFromKeywordFullKeywordGroupKeywordGroupingKeywordGroupsKeywordHashKeywordHavingKeywordIfKeywordIgnoreKeywordInKeywordInnerKeywordIntersectKeywordIntervalKeywordIntoKeywordIsKeywordJoinKeywordLateralKeywordLeftKeywordLikeKeywordLimitKeywordLookupKeywordMergeKeywordNaturalKeywordNewKeywordNoKeywordNotKeywordNullKeywordNullsKeywordOfKeywordOnKeywordOrKeywordOrderKeywordOuterKeywordOverKeywordPartitionKeywordPrecedingKeywordProtoKeywordRangeKeywordRecursiveKeywordRespectKeywordRightKeywordRollupKeywordRowsKeywordSelectKeywordSetKeywordSomeKeywordStructKeywordTablesampleKeywordThenKeywordToKeywordTreatKeywordTrueKeywordUnboundKeywordUnionKeywordUnnestKeywordUsingKeywordWhenKeywordWhereKeywordWindowKeywordWithKeywordWithin"

var _KeywordIndex = [...]uint16{0, 18, 28, 38, 48, 60, 69, 79, 104, 113, 127, 136, 147, 158, 172, 187, 200, 212, 223, 237, 251, 264, 275, 290, 301, 311, 322, 335, 348, 362, 375, 389, 401, 413, 429, 439, 450, 461, 473, 488, 501, 512, 525, 534, 547, 556, 568, 584, 599, 610, 619, 630, 644, 655, 666, 678, 691, 703, 717, 727, 736, 746, 757, 769, 778, 787, 796, 808, 820, 831, 847, 863, 875, 887, 903, 917, 929, 942, 953, 966, 976, 987, 1000, 1018, 1029, 1038, 1050, 1061, 1075, 1087, 1100, 1112, 1123, 1135, 1148, 1159, 1172}

const _KeywordLowerName = "keywordunspecifiedkeywordallkeywordandkeywordanykeywordarraykeywordaskeywordasckeywordassertrowsmodifiedkeywordatkeywordbetweenkeywordbykeywordcasekeywordcastkeywordcollatekeywordcontainskeywordcreatekeywordcrosskeywordcubekeywordcurrentkeyworddefaultkeyworddefinekeyworddesckeyworddistinctkeywordelsekeywordendkeywordenumkeywordescapekeywordexceptkeywordexcludekeywordexistskeywordextractkeywordfalsekeywordfetchkeywordfollowingkeywordforkeywordfromkeywordfullkeywordgroupkeywordgroupingkeywordgroupskeywordhashkeywordhavingkeywordifkeywordignorekeywordinkeywordinnerkeywordintersectkeywordintervalkeywordintokeywordiskeywordjoinkeywordlateralkeywordleftkeywordlikekeywordlimitkeywordlookupkeywordmergekeywordnaturalkeywordnewkeywordnokeywordnotkeywordnullkeywordnullskeywordofkeywordonkeywordorkeywordorderkeywordouterkeywordoverkeywordpartitionkeywordprecedingkeywordprotokeywordrangekeywordrecursivekeywordrespectkeywordrightkeywordrollupkeywordrowskeywordselectkeywordsetkeywordsomekeywordstructkeywordtablesamplekeywordthenkeywordtokeywordtreatkeywordtruekeywordunboundkeywordunionkeywordunnestkeywordusingkeywordwhenkeywordwherekeywordwindowkeywordwithkeywordwithin"

func (i Keyword) String() string {
	if i < 0 || i >= Keyword(len(_KeywordIndex)-1) {
		return fmt.Sprintf("Keyword(%d)", i)
	}
	return _KeywordName[_KeywordIndex[i]:_KeywordIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KeywordNoOp() {
	var x [1]struct{}
	_ = x[KeywordUnspecified-(0)]
	_ = x[KeywordAll-(1)]
	_ = x[KeywordAnd-(2)]
	_ = x[KeywordAny-(3)]
	_ = x[KeywordArray-(4)]
	_ = x[KeywordAs-(5)]
	_ = x[KeywordAsc-(6)]
	_ = x[KeywordAssertRowsModified-(7)]
	_ = x[KeywordAt-(8)]
	_ = x[KeywordBetween-(9)]
	_ = x[KeywordBy-(10)]
	_ = x[KeywordCase-(11)]
	_ = x[KeywordCast-(12)]
	_ = x[KeywordCollate-(13)]
	_ = x[KeywordContains-(14)]
	_ = x[KeywordCreate-(15)]
	_ = x[KeywordCross-(16)]
	_ = x[KeywordCube-(17)]
	_ = x[KeywordCurrent-(18)]
	_ = x[KeywordDefault-(19)]
	_ = x[KeywordDefine-(20)]
	_ = x[KeywordDesc-(21)]
	_ = x[KeywordDistinct-(22)]
	_ = x[KeywordElse-(23)]
	_ = x[KeywordEnd-(24)]
	_ = x[KeywordEnum-(25)]
	_ = x[KeywordEscape-(26)]
	_ = x[KeywordExcept-(27)]
	_ = x[KeywordExclude-(28)]
	_ = x[KeywordExists-(29)]
	_ = x[KeywordExtract-(30)]
	_ = x[KeywordFalse-(31)]
	_ = x[KeywordFetch-(32)]
	_ = x[KeywordFollowing-(33)]
	_ = x[KeywordFor-(34)]
	_ = x[KeywordFrom-(35)]
	_ = x[KeywordFull-(36)]
	_ = x[KeywordGroup-(37)]
	_ = x[KeywordGrouping-(38)]
	_ = x[KeywordGroups-(39)]
	_ = x[KeywordHash-(40)]
	_ = x[KeywordHaving-(41)]
	_ = x[KeywordIf-(42)]
	_ = x[KeywordIgnore-(43)]
	_ = x[KeywordIn-(44)]
	_ = x[KeywordInner-(45)]
	_ = x[KeywordIntersect-(46)]
	_ = x[KeywordInterval-(47)]
	_ = x[KeywordInto-(48)]
	_ = x[KeywordIs-(49)]
	_ = x[KeywordJoin-(50)]
	_ = x[KeywordLateral-(51)]
	_ = x[KeywordLeft-(52)]
	_ = x[KeywordLike-(53)]
	_ = x[KeywordLimit-(54)]
	_ = x[KeywordLookup-(55)]
	_ = x[KeywordMerge-(56)]
	_ = x[KeywordNatural-(57)]
	_ = x[KeywordNew-(58)]
	_ = x[KeywordNo-(59)]
	_ = x[KeywordNot-(60)]
	_ = x[KeywordNull-(61)]
	_ = x[KeywordNulls-(62)]
	_ = x[KeywordOf-(63)]
	_ = x[KeywordOn-(64)]
	_ = x[KeywordOr-(65)]
	_ = x[KeywordOrder-(66)]
	_ = x[KeywordOuter-(67)]
	_ = x[KeywordOver-(68)]
	_ = x[KeywordPartition-(69)]
	_ = x[KeywordPreceding-(70)]
	_ = x[KeywordProto-(71)]
	_ = x[KeywordRange-(72)]
	_ = x[KeywordRecursive-(73)]
	_ = x[KeywordRespect-(74)]
	_ = x[KeywordRight-(75)]
	_ = x[KeywordRollup-(76)]
	_ = x[KeywordRows-(77)]
	_ = x[KeywordSelect-(78)]
	_ = x[KeywordSet-(79)]
	_ = x[KeywordSome-(80)]
	_ = x[KeywordStruct-(81)]
	_ = x[KeywordTablesample-(82)]
	_ = x[KeywordThen-(83)]
	_ = x[KeywordTo-(84)]
	_ = x[KeywordTreat-(85)]
	_ = x[KeywordTrue-(86)]
	_ = x[KeywordUnbound-(87)]
	_ = x[KeywordUnion-(88)]
	_ = x[KeywordUnnest-(89)]
	_ = x[KeywordUsing-(90)]
	_ = x[KeywordWhen-(91)]
	_ = x[KeywordWhere-(92)]
	_ = x[KeywordWindow-(93)]
	_ = x[KeywordWith-(94)]
	_ = x[KeywordWithin-(95)]
}

var _KeywordValues = []Keyword{KeywordUnspecified, KeywordAll, KeywordAnd, KeywordAny, KeywordArray, KeywordAs, KeywordAsc, KeywordAssertRowsModified, KeywordAt, KeywordBetween, KeywordBy, KeywordCase, KeywordCast, KeywordCollate, KeywordContains, KeywordCreate, KeywordCross, KeywordCube, KeywordCurrent, KeywordDefault, KeywordDefine, KeywordDesc, KeywordDistinct, KeywordElse, KeywordEnd, KeywordEnum, KeywordEscape, KeywordExcept, KeywordExclude, KeywordExists, KeywordExtract, KeywordFalse, KeywordFetch, KeywordFollowing, KeywordFor, KeywordFrom, KeywordFull, KeywordGroup, KeywordGrouping, KeywordGroups, KeywordHash, KeywordHaving, KeywordIf, KeywordIgnore, KeywordIn, KeywordInner, KeywordIntersect, KeywordInterval, KeywordInto, KeywordIs, KeywordJoin, KeywordLateral, KeywordLeft, KeywordLike, KeywordLimit, KeywordLookup, KeywordMerge, KeywordNatural, KeywordNew, KeywordNo, KeywordNot, KeywordNull, KeywordNulls, KeywordOf, KeywordOn, KeywordOr, KeywordOrder, KeywordOuter, KeywordOver, KeywordPartition, KeywordPreceding, KeywordProto, KeywordRange, KeywordRecursive, KeywordRespect, KeywordRight, KeywordRollup, KeywordRows, KeywordSelect, KeywordSet, KeywordSome, KeywordStruct, KeywordTablesample, KeywordThen, KeywordTo, KeywordTreat, KeywordTrue, KeywordUnbound, KeywordUnion, KeywordUnnest, KeywordUsing, KeywordWhen, KeywordWhere, KeywordWindow, KeywordWith, KeywordWithin}

var _KeywordNameToValueMap = map[string]Keyword{
	_KeywordName[0:18]:           KeywordUnspecified,
	_KeywordLowerName[0:18]:      KeywordUnspecified,
	_KeywordName[18:28]:          KeywordAll,
	_KeywordLowerName[18:28]:     KeywordAll,
	_KeywordName[28:38]:          KeywordAnd,
	_KeywordLowerName[28:38]:     KeywordAnd,
	_KeywordName[38:48]:          KeywordAny,
	_KeywordLowerName[38:48]:     KeywordAny,
	_KeywordName[48:60]:          KeywordArray,
	_KeywordLowerName[48:60]:     KeywordArray,
	_KeywordName[60:69]:          KeywordAs,
	_KeywordLowerName[60:69]:     KeywordAs,
	_KeywordName[69:79]:          KeywordAsc,
	_KeywordLowerName[69:79]:     KeywordAsc,
	_KeywordName[79:104]:         KeywordAssertRowsModified,
	_KeywordLowerName[79:104]:    KeywordAssertRowsModified,
	_KeywordName[104:113]:        KeywordAt,
	_KeywordLowerName[104:113]:   KeywordAt,
	_KeywordName[113:127]:        KeywordBetween,
	_KeywordLowerName[113:127]:   KeywordBetween,
	_KeywordName[127:136]:        KeywordBy,
	_KeywordLowerName[127:136]:   KeywordBy,
	_KeywordName[136:147]:        KeywordCase,
	_KeywordLowerName[136:147]:   KeywordCase,
	_KeywordName[147:158]:        KeywordCast,
	_KeywordLowerName[147:158]:   KeywordCast,
	_KeywordName[158:172]:        KeywordCollate,
	_KeywordLowerName[158:172]:   KeywordCollate,
	_KeywordName[172:187]:        KeywordContains,
	_KeywordLowerName[172:187]:   KeywordContains,
	_KeywordName[187:200]:        KeywordCreate,
	_KeywordLowerName[187:200]:   KeywordCreate,
	_KeywordName[200:212]:        KeywordCross,
	_KeywordLowerName[200:212]:   KeywordCross,
	_KeywordName[212:223]:        KeywordCube,
	_KeywordLowerName[212:223]:   KeywordCube,
	_KeywordName[223:237]:        KeywordCurrent,
	_KeywordLowerName[223:237]:   KeywordCurrent,
	_KeywordName[237:251]:        KeywordDefault,
	_KeywordLowerName[237:251]:   KeywordDefault,
	_KeywordName[251:264]:        KeywordDefine,
	_KeywordLowerName[251:264]:   KeywordDefine,
	_KeywordName[264:275]:        KeywordDesc,
	_KeywordLowerName[264:275]:   KeywordDesc,
	_KeywordName[275:290]:        KeywordDistinct,
	_KeywordLowerName[275:290]:   KeywordDistinct,
	_KeywordName[290:301]:        KeywordElse,
	_KeywordLowerName[290:301]:   KeywordElse,
	_KeywordName[301:311]:        KeywordEnd,
	_KeywordLowerName[301:311]:   KeywordEnd,
	_KeywordName[311:322]:        KeywordEnum,
	_KeywordLowerName[311:322]:   KeywordEnum,
	_KeywordName[322:335]:        KeywordEscape,
	_KeywordLowerName[322:335]:   KeywordEscape,
	_KeywordName[335:348]:        KeywordExcept,
	_KeywordLowerName[335:348]:   KeywordExcept,
	_KeywordName[348:362]:        KeywordExclude,
	_KeywordLowerName[348:362]:   KeywordExclude,
	_KeywordName[362:375]:        KeywordExists,
	_KeywordLowerName[362:375]:   KeywordExists,
	_KeywordName[375:389]:        KeywordExtract,
	_KeywordLowerName[375:389]:   KeywordExtract,
	_KeywordName[389:401]:        KeywordFalse,
	_KeywordLowerName[389:401]:   KeywordFalse,
	_KeywordName[401:413]:        KeywordFetch,
	_KeywordLowerName[401:413]:   KeywordFetch,
	_KeywordName[413:429]:        KeywordFollowing,
	_KeywordLowerName[413:429]:   KeywordFollowing,
	_KeywordName[429:439]:        KeywordFor,
	_KeywordLowerName[429:439]:   KeywordFor,
	_KeywordName[439:450]:        KeywordFrom,
	_KeywordLowerName[439:450]:   KeywordFrom,
	_KeywordName[450:461]:        KeywordFull,
	_KeywordLowerName[450:461]:   KeywordFull,
	_KeywordName[461:473]:        KeywordGroup,
	_KeywordLowerName[461:473]:   KeywordGroup,
	_KeywordName[473:488]:        KeywordGrouping,
	_KeywordLowerName[473:488]:   KeywordGrouping,
	_KeywordName[488:501]:        KeywordGroups,
	_KeywordLowerName[488:501]:   KeywordGroups,
	_KeywordName[501:512]:        KeywordHash,
	_KeywordLowerName[501:512]:   KeywordHash,
	_KeywordName[512:525]:        KeywordHaving,
	_KeywordLowerName[512:525]:   KeywordHaving,
	_KeywordName[525:534]:        KeywordIf,
	_KeywordLowerName[525:534]:   KeywordIf,
	_KeywordName[534:547]:        KeywordIgnore,
	_KeywordLowerName[534:547]:   KeywordIgnore,
	_KeywordName[547:556]:        KeywordIn,
	_KeywordLowerName[547:556]:   KeywordIn,
	_KeywordName[556:568]:        KeywordInner,
	_KeywordLowerName[556:568]:   KeywordInner,
	_KeywordName[568:584]:        KeywordIntersect,
	_KeywordLowerName[568:584]:   KeywordIntersect,
	_KeywordName[584:599]:        KeywordInterval,
	_KeywordLowerName[584:599]:   KeywordInterval,
	_KeywordName[599:610]:        KeywordInto,
	_KeywordLowerName[599:610]:   KeywordInto,
	_KeywordName[610:619]:        KeywordIs,
	_KeywordLowerName[610:619]:   KeywordIs,
	_KeywordName[619:630]:        KeywordJoin,
	_KeywordLowerName[619:630]:   KeywordJoin,
	_KeywordName[630:644]:        KeywordLateral,
	_KeywordLowerName[630:644]:   KeywordLateral,
	_KeywordName[644:655]:        KeywordLeft,
	_KeywordLowerName[644:655]:   KeywordLeft,
	_KeywordName[655:666]:        KeywordLike,
	_KeywordLowerName[655:666]:   KeywordLike,
	_KeywordName[666:678]:        KeywordLimit,
	_KeywordLowerName[666:678]:   KeywordLimit,
	_KeywordName[678:691]:        KeywordLookup,
	_KeywordLowerName[678:691]:   KeywordLookup,
	_KeywordName[691:703]:        KeywordMerge,
	_KeywordLowerName[691:703]:   KeywordMerge,
	_KeywordName[703:717]:        KeywordNatural,
	_KeywordLowerName[703:717]:   KeywordNatural,
	_KeywordName[717:727]:        KeywordNew,
	_KeywordLowerName[717:727]:   KeywordNew,
	_KeywordName[727:736]:        KeywordNo,
	_KeywordLowerName[727:736]:   KeywordNo,
	_KeywordName[736:746]:        KeywordNot,
	_KeywordLowerName[736:746]:   KeywordNot,
	_KeywordName[746:757]:        KeywordNull,
	_KeywordLowerName[746:757]:   KeywordNull,
	_KeywordName[757:769]:        KeywordNulls,
	_KeywordLowerName[757:769]:   KeywordNulls,
	_KeywordName[769:778]:        KeywordOf,
	_KeywordLowerName[769:778]:   KeywordOf,
	_KeywordName[778:787]:        KeywordOn,
	_KeywordLowerName[778:787]:   KeywordOn,
	_KeywordName[787:796]:        KeywordOr,
	_KeywordLowerName[787:796]:   KeywordOr,
	_KeywordName[796:808]:        KeywordOrder,
	_KeywordLowerName[796:808]:   KeywordOrder,
	_KeywordName[808:820]:        KeywordOuter,
	_KeywordLowerName[808:820]:   KeywordOuter,
	_KeywordName[820:831]:        KeywordOver,
	_KeywordLowerName[820:831]:   KeywordOver,
	_KeywordName[831:847]:        KeywordPartition,
	_KeywordLowerName[831:847]:   KeywordPartition,
	_KeywordName[847:863]:        KeywordPreceding,
	_KeywordLowerName[847:863]:   KeywordPreceding,
	_KeywordName[863:875]:        KeywordProto,
	_KeywordLowerName[863:875]:   KeywordProto,
	_KeywordName[875:887]:        KeywordRange,
	_KeywordLowerName[875:887]:   KeywordRange,
	_KeywordName[887:903]:        KeywordRecursive,
	_KeywordLowerName[887:903]:   KeywordRecursive,
	_KeywordName[903:917]:        KeywordRespect,
	_KeywordLowerName[903:917]:   KeywordRespect,
	_KeywordName[917:929]:        KeywordRight,
	_KeywordLowerName[917:929]:   KeywordRight,
	_KeywordName[929:942]:        KeywordRollup,
	_KeywordLowerName[929:942]:   KeywordRollup,
	_KeywordName[942:953]:        KeywordRows,
	_KeywordLowerName[942:953]:   KeywordRows,
	_KeywordName[953:966]:        KeywordSelect,
	_KeywordLowerName[953:966]:   KeywordSelect,
	_KeywordName[966:976]:        KeywordSet,
	_KeywordLowerName[966:976]:   KeywordSet,
	_KeywordName[976:987]:        KeywordSome,
	_KeywordLowerName[976:987]:   KeywordSome,
	_KeywordName[987:1000]:       KeywordStruct,
	_KeywordLowerName[987:1000]:  KeywordStruct,
	_KeywordName[1000:1018]:      KeywordTablesample,
	_KeywordLowerName[1000:1018]: KeywordTablesample,
	_KeywordName[1018:1029]:      KeywordThen,
	_KeywordLowerName[1018:1029]: KeywordThen,
	_KeywordName[1029:1038]:      KeywordTo,
	_KeywordLowerName[1029:1038]: KeywordTo,
	_KeywordName[1038:1050]:      KeywordTreat,
	_KeywordLowerName[1038:1050]: KeywordTreat,
	_KeywordName[1050:1061]:      KeywordTrue,
	_KeywordLowerName[1050:1061]: KeywordTrue,
	_KeywordName[1061:1075]:      KeywordUnbound,
	_KeywordLowerName[1061:1075]: KeywordUnbound,
	_KeywordName[1075:1087]:      KeywordUnion,
	_KeywordLowerName[1075:1087]: KeywordUnion,
	_KeywordName[1087:1100]:      KeywordUnnest,
	_KeywordLowerName[1087:1100]: KeywordUnnest,
	_KeywordName[1100:1112]:      KeywordUsing,
	_KeywordLowerName[1100:1112]: KeywordUsing,
	_KeywordName[1112:1123]:      KeywordWhen,
	_KeywordLowerName[1112:1123]: KeywordWhen,
	_KeywordName[1123:1135]:      KeywordWhere,
	_KeywordLowerName[1123:1135]: KeywordWhere,
	_KeywordName[1135:1148]:      KeywordWindow,
	_KeywordLowerName[1135:1148]: KeywordWindow,
	_KeywordName[1148:1159]:      KeywordWith,
	_KeywordLowerName[1148:1159]: KeywordWith,
	_KeywordName[1159:1172]:      KeywordWithin,
	_KeywordLowerName[1159:1172]: KeywordWithin,
}

var _KeywordNames = []string{
	_KeywordName[0:18],
	_KeywordName[18:28],
	_KeywordName[28:38],
	_KeywordName[38:48],
	_KeywordName[48:60],
	_KeywordName[60:69],
	_KeywordName[69:79],
	_KeywordName[79:104],
	_KeywordName[104:113],
	_KeywordName[113:127],
	_KeywordName[127:136],
	_KeywordName[136:147],
	_KeywordName[147:158],
	_KeywordName[158:172],
	_KeywordName[172:187],
	_KeywordName[187:200],
	_KeywordName[200:212],
	_KeywordName[212:223],
	_KeywordName[223:237],
	_KeywordName[237:251],
	_KeywordName[251:264],
	_KeywordName[264:275],
	_KeywordName[275:290],
	_KeywordName[290:301],
	_KeywordName[301:311],
	_KeywordName[311:322],
	_KeywordName[322:335],
	_KeywordName[335:348],
	_KeywordName[348:362],
	_KeywordName[362:375],
	_KeywordName[375:389],
	_KeywordName[389:401],
	_KeywordName[401:413],
	_KeywordName[413:429],
	_KeywordName[429:439],
	_KeywordName[439:450],
	_KeywordName[450:461],
	_KeywordName[461:473],
	_KeywordName[473:488],
	_KeywordName[488:501],
	_KeywordName[501:512],
	_KeywordName[512:525],
	_KeywordName[525:534],
	_KeywordName[534:547],
	_KeywordName[547:556],
	_KeywordName[556:568],
	_KeywordName[568:584],
	_KeywordName[584:599],
	_KeywordName[599:610],
	_KeywordName[610:619],
	_KeywordName[619:630],
	_KeywordName[630:644],
	_KeywordName[644:655],
	_KeywordName[655:666],
	_KeywordName[666:678],
	_KeywordName[678:691],
	_KeywordName[691:703],
	_KeywordName[703:717],
	_KeywordName[717:727],
	_KeywordName[727:736],
	_KeywordName[736:746],
	_KeywordName[746:757],
	_KeywordName[757:769],
	_KeywordName[769:778],
	_KeywordName[778:787],
	_KeywordName[787:796],
	_KeywordName[796:808],
	_KeywordName[808:820],
	_KeywordName[820:831],
	_KeywordName[831:847],
	_KeywordName[847:863],
	_KeywordName[863:875],
	_KeywordName[875:887],
	_KeywordName[887:903],
	_KeywordName[903:917],
	_KeywordName[917:929],
	_KeywordName[929:942],
	_KeywordName[942:953],
	_KeywordName[953:966],
	_KeywordName[966:976],
	_KeywordName[976:987],
	_KeywordName[987:1000],
	_KeywordName[1000:1018],
	_KeywordName[1018:1029],
	_KeywordName[1029:1038],
	_KeywordName[1038:1050],
	_KeywordName[1050:1061],
	_KeywordName[1061:1075],
	_KeywordName[1075:1087],
	_KeywordName[1087:1100],
	_KeywordName[1100:1112],
	_KeywordName[1112:1123],
	_KeywordName[1123:1135],
	_KeywordName[1135:1148],
	_KeywordName[1148:1159],
	_KeywordName[1159:1172],
}

// KeywordString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KeywordString(s string) (Keyword, error) {
	if val, ok := _KeywordNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KeywordNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Keyword values", s)
}

// KeywordValues returns all values of the enum
func KeywordValues() []Keyword {
	return _KeywordValues
}

// KeywordStrings returns a slice of all String values of the enum
func KeywordStrings() []string {
	strs := make([]string, len(_KeywordNames))
	copy(strs, _KeywordNames)
	return strs
}

// IsAKeyword returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Keyword) IsAKeyword() bool {
	for _, v := range _KeywordValues {
		if i == v {
			return true
		}
	}
	return false
}
