// Code generated by "stringer -type ConstraintKind constraint.go"; DO NOT EDIT.

package ddl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConstraintKindUnspecified-0]
	_ = x[ConstraintKindCheck-1]
	_ = x[ConstraintKindForeignKey-2]
}

const _ConstraintKind_name = "ConstraintKindUnspecifiedConstraintKindCheckConstraintKindForeignKey"

var _ConstraintKind_index = [...]uint8{0, 25, 44, 68}

func (i ConstraintKind) String() string {
	if i < 0 || i >= ConstraintKind(len(_ConstraintKind_index)-1) {
		return "ConstraintKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstraintKind_name[_ConstraintKind_index[i]:_ConstraintKind_index[i+1]]
}
