// Code generated by "stringer -type OnDeleteAction on_delete_action.go"; DO NOT EDIT.

package ddl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OnDeleteNoAction-0]
	_ = x[OnDeleteCascade-1]
}

const _OnDeleteAction_name = "OnDeleteNoActionOnDeleteCascade"

var _OnDeleteAction_index = [...]uint8{0, 16, 31}

func (i OnDeleteAction) String() string {
	if i < 0 || i >= OnDeleteAction(len(_OnDeleteAction_index)-1) {
		return "OnDeleteAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OnDeleteAction_name[_OnDeleteAction_index[i]:_OnDeleteAction_index[i+1]]
}
