// Code generated by "stringer -type Order order.go"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderASC-0]
	_ = x[OrderDESC-1]
}

const _Order_name = "OrderASCOrderDESC"

var _Order_index = [...]uint8{0, 8, 17}

func (i Order) String() string {
	if i < 0 || i >= Order(len(_Order_index)-1) {
		return "Order(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Order_name[_Order_index[i]:_Order_index[i+1]]
}
