// Code generated by "stringer -type TypeCode type_code.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCodeUnspecified-0]
	_ = x[TypeCodeArray-1]
	_ = x[TypeCodeBool-2]
	_ = x[TypeCodeBytes-3]
	_ = x[TypeCodeDate-4]
	_ = x[TypeCodeJSON-5]
	_ = x[TypeCodeInt64-6]
	_ = x[TypeCodeNumeric-7]
	_ = x[TypeCodeFloat64-8]
	_ = x[TypeCodeString-9]
	_ = x[TypeCodeStruct-10]
	_ = x[TypeCodeTimestamp-11]
}

const _TypeCode_name = "TypeCodeUnspecifiedTypeCodeArrayTypeCodeBoolTypeCodeBytesTypeCodeDateTypeCodeJSONTypeCodeInt64TypeCodeNumericTypeCodeFloat64TypeCodeStringTypeCodeStructTypeCodeTimestamp"

var _TypeCode_index = [...]uint8{0, 19, 32, 44, 57, 69, 81, 94, 109, 124, 138, 152, 169}

func (i TypeCode) String() string {
	if i < 0 || i >= TypeCode(len(_TypeCode_index)-1) {
		return "TypeCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeCode_name[_TypeCode_index[i]:_TypeCode_index[i+1]]
}
